### ISSUE TITLE
Can't login to app

### ISSUE THREAD

**Issue by toptalo** [Kondenko/pocketwaka#3]
After login on site shows error in UI

![Screenshot_20230201-004624](https://user-images.githubusercontent.com/2378757/215890876-fd28ec85-2fe5-4653-9015-da610b910f04.png)

![Screenshot_20230201-004633](https://user-images.githubusercontent.com/2378757/215890952-2d88cabf-b6e6-48a6-8aaf-a99f5a9a1820.png)

![Screenshot_20230201-004639](https://user-images.githubusercontent.com/2378757/215890985-87a270f1-c629-4633-b596-04377dc8b248.png)

**Comment by ShanelkaPramuditha** [comment]
Yes can't log in to app. log in failed error.

**Comment by Kondenko** [comment]
Thank you @toptalo, I'll be posting updates to issue https://github.com/Kondenko/pocketwaka/issues/4

**Comment by toptalo** [comment]
Thank you!
