### ISSUE TITLE
Log in Failed

### ISSUE THREAD

**Issue by ShanelkaPramuditha** [Kondenko/pocketwaka#4]
Can't log in to app. Its display logging failed error

**Comment by LegitCamper** [comment]
I receive the same issue. In waka time I can see my account is connected to pocketwaka, but still cannot auth in the app

**Comment by Kondenko** [comment]
https://github.com/Kondenko/pocketwaka/issues/3 / https://github.com/Kondenko/pocketwaka/issues/4
Thanks everyone for letting me know. I'll investigate the bug.

**Comment by Kondenko** [comment]
Found the problem. Wakatime Oauth API started returning HTML instead of JSON for some reason. I've added a workaround for this, now I only have to fix all the problems that arose after API changes and updating some necessary dependencies 😅Stay tuned

**Comment by Kondenko** [comment]
The fix has passed the review on the Play Store, I'll gradually roll it out in the upcoming days. Thanks everyone!
